// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: rpc.proto

package running_trackerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TrainersServiceClient is the client API for TrainersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrainersServiceClient interface {
	AddTrainers(ctx context.Context, in *AddTrainersRequest, opts ...grpc.CallOption) (*AddTrainersResponse, error)
	GetTrainers(ctx context.Context, in *GetTrainersRequest, opts ...grpc.CallOption) (*GetTrainersResponse, error)
	UpdateTrainers(ctx context.Context, in *UpdateTrainersRequest, opts ...grpc.CallOption) (*UpdateTrainersResponse, error)
	DeleteTrainers(ctx context.Context, in *DeleteTrainersRequest, opts ...grpc.CallOption) (*DeleteTrainersResponse, error)
}

type trainersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrainersServiceClient(cc grpc.ClientConnInterface) TrainersServiceClient {
	return &trainersServiceClient{cc}
}

func (c *trainersServiceClient) AddTrainers(ctx context.Context, in *AddTrainersRequest, opts ...grpc.CallOption) (*AddTrainersResponse, error) {
	out := new(AddTrainersResponse)
	err := c.cc.Invoke(ctx, "/main.TrainersService/add_trainers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainersServiceClient) GetTrainers(ctx context.Context, in *GetTrainersRequest, opts ...grpc.CallOption) (*GetTrainersResponse, error) {
	out := new(GetTrainersResponse)
	err := c.cc.Invoke(ctx, "/main.TrainersService/get_trainers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainersServiceClient) UpdateTrainers(ctx context.Context, in *UpdateTrainersRequest, opts ...grpc.CallOption) (*UpdateTrainersResponse, error) {
	out := new(UpdateTrainersResponse)
	err := c.cc.Invoke(ctx, "/main.TrainersService/update_trainers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainersServiceClient) DeleteTrainers(ctx context.Context, in *DeleteTrainersRequest, opts ...grpc.CallOption) (*DeleteTrainersResponse, error) {
	out := new(DeleteTrainersResponse)
	err := c.cc.Invoke(ctx, "/main.TrainersService/delete_trainers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrainersServiceServer is the server API for TrainersService service.
// All implementations should embed UnimplementedTrainersServiceServer
// for forward compatibility
type TrainersServiceServer interface {
	AddTrainers(context.Context, *AddTrainersRequest) (*AddTrainersResponse, error)
	GetTrainers(context.Context, *GetTrainersRequest) (*GetTrainersResponse, error)
	UpdateTrainers(context.Context, *UpdateTrainersRequest) (*UpdateTrainersResponse, error)
	DeleteTrainers(context.Context, *DeleteTrainersRequest) (*DeleteTrainersResponse, error)
}

// UnimplementedTrainersServiceServer should be embedded to have forward compatible implementations.
type UnimplementedTrainersServiceServer struct {
}

func (UnimplementedTrainersServiceServer) AddTrainers(context.Context, *AddTrainersRequest) (*AddTrainersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTrainers not implemented")
}
func (UnimplementedTrainersServiceServer) GetTrainers(context.Context, *GetTrainersRequest) (*GetTrainersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrainers not implemented")
}
func (UnimplementedTrainersServiceServer) UpdateTrainers(context.Context, *UpdateTrainersRequest) (*UpdateTrainersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTrainers not implemented")
}
func (UnimplementedTrainersServiceServer) DeleteTrainers(context.Context, *DeleteTrainersRequest) (*DeleteTrainersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTrainers not implemented")
}

// UnsafeTrainersServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrainersServiceServer will
// result in compilation errors.
type UnsafeTrainersServiceServer interface {
	mustEmbedUnimplementedTrainersServiceServer()
}

func RegisterTrainersServiceServer(s grpc.ServiceRegistrar, srv TrainersServiceServer) {
	s.RegisterService(&TrainersService_ServiceDesc, srv)
}

func _TrainersService_AddTrainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTrainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainersServiceServer).AddTrainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.TrainersService/add_trainers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainersServiceServer).AddTrainers(ctx, req.(*AddTrainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainersService_GetTrainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainersServiceServer).GetTrainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.TrainersService/get_trainers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainersServiceServer).GetTrainers(ctx, req.(*GetTrainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainersService_UpdateTrainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTrainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainersServiceServer).UpdateTrainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.TrainersService/update_trainers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainersServiceServer).UpdateTrainers(ctx, req.(*UpdateTrainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainersService_DeleteTrainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTrainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainersServiceServer).DeleteTrainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.TrainersService/delete_trainers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainersServiceServer).DeleteTrainers(ctx, req.(*DeleteTrainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrainersService_ServiceDesc is the grpc.ServiceDesc for TrainersService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrainersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.TrainersService",
	HandlerType: (*TrainersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "add_trainers",
			Handler:    _TrainersService_AddTrainers_Handler,
		},
		{
			MethodName: "get_trainers",
			Handler:    _TrainersService_GetTrainers_Handler,
		},
		{
			MethodName: "update_trainers",
			Handler:    _TrainersService_UpdateTrainers_Handler,
		},
		{
			MethodName: "delete_trainers",
			Handler:    _TrainersService_DeleteTrainers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

// ActivitiesServiceClient is the client API for ActivitiesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ActivitiesServiceClient interface {
	AddActivities(ctx context.Context, in *AddActivitiesRequest, opts ...grpc.CallOption) (*AddActivitiesResponse, error)
	GetActivities(ctx context.Context, in *GetActivitiesRequest, opts ...grpc.CallOption) (*GetActivitiesResponse, error)
}

type activitiesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewActivitiesServiceClient(cc grpc.ClientConnInterface) ActivitiesServiceClient {
	return &activitiesServiceClient{cc}
}

func (c *activitiesServiceClient) AddActivities(ctx context.Context, in *AddActivitiesRequest, opts ...grpc.CallOption) (*AddActivitiesResponse, error) {
	out := new(AddActivitiesResponse)
	err := c.cc.Invoke(ctx, "/main.ActivitiesService/add_activities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activitiesServiceClient) GetActivities(ctx context.Context, in *GetActivitiesRequest, opts ...grpc.CallOption) (*GetActivitiesResponse, error) {
	out := new(GetActivitiesResponse)
	err := c.cc.Invoke(ctx, "/main.ActivitiesService/get_activities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivitiesServiceServer is the server API for ActivitiesService service.
// All implementations should embed UnimplementedActivitiesServiceServer
// for forward compatibility
type ActivitiesServiceServer interface {
	AddActivities(context.Context, *AddActivitiesRequest) (*AddActivitiesResponse, error)
	GetActivities(context.Context, *GetActivitiesRequest) (*GetActivitiesResponse, error)
}

// UnimplementedActivitiesServiceServer should be embedded to have forward compatible implementations.
type UnimplementedActivitiesServiceServer struct {
}

func (UnimplementedActivitiesServiceServer) AddActivities(context.Context, *AddActivitiesRequest) (*AddActivitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddActivities not implemented")
}
func (UnimplementedActivitiesServiceServer) GetActivities(context.Context, *GetActivitiesRequest) (*GetActivitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActivities not implemented")
}

// UnsafeActivitiesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActivitiesServiceServer will
// result in compilation errors.
type UnsafeActivitiesServiceServer interface {
	mustEmbedUnimplementedActivitiesServiceServer()
}

func RegisterActivitiesServiceServer(s grpc.ServiceRegistrar, srv ActivitiesServiceServer) {
	s.RegisterService(&ActivitiesService_ServiceDesc, srv)
}

func _ActivitiesService_AddActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddActivitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivitiesServiceServer).AddActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.ActivitiesService/add_activities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivitiesServiceServer).AddActivities(ctx, req.(*AddActivitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivitiesService_GetActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActivitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivitiesServiceServer).GetActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.ActivitiesService/get_activities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivitiesServiceServer).GetActivities(ctx, req.(*GetActivitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ActivitiesService_ServiceDesc is the grpc.ServiceDesc for ActivitiesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ActivitiesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.ActivitiesService",
	HandlerType: (*ActivitiesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "add_activities",
			Handler:    _ActivitiesService_AddActivities_Handler,
		},
		{
			MethodName: "get_activities",
			Handler:    _ActivitiesService_GetActivities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

// HealthCheckServiceClient is the client API for HealthCheckService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthCheckServiceClient interface {
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type healthCheckServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthCheckServiceClient(cc grpc.ClientConnInterface) HealthCheckServiceClient {
	return &healthCheckServiceClient{cc}
}

func (c *healthCheckServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/main.HealthCheckService/health_check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthCheckServiceServer is the server API for HealthCheckService service.
// All implementations should embed UnimplementedHealthCheckServiceServer
// for forward compatibility
type HealthCheckServiceServer interface {
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
}

// UnimplementedHealthCheckServiceServer should be embedded to have forward compatible implementations.
type UnimplementedHealthCheckServiceServer struct {
}

func (UnimplementedHealthCheckServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}

// UnsafeHealthCheckServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthCheckServiceServer will
// result in compilation errors.
type UnsafeHealthCheckServiceServer interface {
	mustEmbedUnimplementedHealthCheckServiceServer()
}

func RegisterHealthCheckServiceServer(s grpc.ServiceRegistrar, srv HealthCheckServiceServer) {
	s.RegisterService(&HealthCheckService_ServiceDesc, srv)
}

func _HealthCheckService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthCheckServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.HealthCheckService/health_check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthCheckServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HealthCheckService_ServiceDesc is the grpc.ServiceDesc for HealthCheckService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthCheckService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.HealthCheckService",
	HandlerType: (*HealthCheckServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "health_check",
			Handler:    _HealthCheckService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
