// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: trainers.proto

package running_trackerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SurfaceType int32

const (
	SurfaceType_UNSPECIFIED   SurfaceType = 0
	SurfaceType_ROAD          SurfaceType = 1
	SurfaceType_TRAIL         SurfaceType = 2
	SurfaceType_ROAD_TO_TRAIL SurfaceType = 3
	SurfaceType_TREADMILL     SurfaceType = 4
)

// Enum value maps for SurfaceType.
var (
	SurfaceType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "ROAD",
		2: "TRAIL",
		3: "ROAD_TO_TRAIL",
		4: "TREADMILL",
	}
	SurfaceType_value = map[string]int32{
		"UNSPECIFIED":   0,
		"ROAD":          1,
		"TRAIL":         2,
		"ROAD_TO_TRAIL": 3,
		"TREADMILL":     4,
	}
)

func (x SurfaceType) Enum() *SurfaceType {
	p := new(SurfaceType)
	*p = x
	return p
}

func (x SurfaceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SurfaceType) Descriptor() protoreflect.EnumDescriptor {
	return file_trainers_proto_enumTypes[0].Descriptor()
}

func (SurfaceType) Type() protoreflect.EnumType {
	return &file_trainers_proto_enumTypes[0]
}

func (x SurfaceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SurfaceType.Descriptor instead.
func (SurfaceType) EnumDescriptor() ([]byte, []int) {
	return file_trainers_proto_rawDescGZIP(), []int{0}
}

type TrainerStatus int32

const (
	TrainerStatus_NEW     TrainerStatus = 0
	TrainerStatus_ACTIVE  TrainerStatus = 1
	TrainerStatus_LOST    TrainerStatus = 2
	TrainerStatus_RETIRED TrainerStatus = 3
)

// Enum value maps for TrainerStatus.
var (
	TrainerStatus_name = map[int32]string{
		0: "NEW",
		1: "ACTIVE",
		2: "LOST",
		3: "RETIRED",
	}
	TrainerStatus_value = map[string]int32{
		"NEW":     0,
		"ACTIVE":  1,
		"LOST":    2,
		"RETIRED": 3,
	}
)

func (x TrainerStatus) Enum() *TrainerStatus {
	p := new(TrainerStatus)
	*p = x
	return p
}

func (x TrainerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrainerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_trainers_proto_enumTypes[1].Descriptor()
}

func (TrainerStatus) Type() protoreflect.EnumType {
	return &file_trainers_proto_enumTypes[1]
}

func (x TrainerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrainerStatus.Descriptor instead.
func (TrainerStatus) EnumDescriptor() ([]byte, []int) {
	return file_trainers_proto_rawDescGZIP(), []int{1}
}

type Trainer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Brand            string        `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Model            string        `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	PurchaseDate     string        `protobuf:"bytes,4,opt,name=purchase_date,json=purchaseDate,proto3" json:"purchase_date,omitempty"`
	ExpectedLifespan int64         `protobuf:"varint,5,opt,name=expected_lifespan,json=expectedLifespan,proto3" json:"expected_lifespan,omitempty"`
	SurfaceType      SurfaceType   `protobuf:"varint,6,opt,name=surface_type,json=surfaceType,proto3,enum=main.SurfaceType" json:"surface_type,omitempty"`
	Status           TrainerStatus `protobuf:"varint,7,opt,name=status,proto3,enum=main.TrainerStatus" json:"status,omitempty"`
}

func (x *Trainer) Reset() {
	*x = Trainer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trainers_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Trainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trainer) ProtoMessage() {}

func (x *Trainer) ProtoReflect() protoreflect.Message {
	mi := &file_trainers_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trainer.ProtoReflect.Descriptor instead.
func (*Trainer) Descriptor() ([]byte, []int) {
	return file_trainers_proto_rawDescGZIP(), []int{0}
}

func (x *Trainer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Trainer) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Trainer) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Trainer) GetPurchaseDate() string {
	if x != nil {
		return x.PurchaseDate
	}
	return ""
}

func (x *Trainer) GetExpectedLifespan() int64 {
	if x != nil {
		return x.ExpectedLifespan
	}
	return 0
}

func (x *Trainer) GetSurfaceType() SurfaceType {
	if x != nil {
		return x.SurfaceType
	}
	return SurfaceType_UNSPECIFIED
}

func (x *Trainer) GetStatus() TrainerStatus {
	if x != nil {
		return x.Status
	}
	return TrainerStatus_NEW
}

var File_trainers_proto protoreflect.FileDescriptor

var file_trainers_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0xfa, 0x01, 0x0a, 0x07, 0x54, 0x72, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x23,
	0x0a, 0x0d, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x44,
	0x61, 0x74, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f,
	0x6c, 0x69, 0x66, 0x65, 0x73, 0x70, 0x61, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10,
	0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x4c, 0x69, 0x66, 0x65, 0x73, 0x70, 0x61, 0x6e,
	0x12, 0x34, 0x0a, 0x0c, 0x73, 0x75, 0x72, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x75,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x73, 0x75, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x54, 0x72,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x2a, 0x55, 0x0a, 0x0b, 0x53, 0x75, 0x72, 0x66, 0x61, 0x63, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x4f, 0x41, 0x44, 0x10, 0x01, 0x12, 0x09, 0x0a,
	0x05, 0x54, 0x52, 0x41, 0x49, 0x4c, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x4f, 0x41, 0x44,
	0x5f, 0x54, 0x4f, 0x5f, 0x54, 0x52, 0x41, 0x49, 0x4c, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x54,
	0x52, 0x45, 0x41, 0x44, 0x4d, 0x49, 0x4c, 0x4c, 0x10, 0x04, 0x2a, 0x3b, 0x0a, 0x0d, 0x54, 0x72,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x07, 0x0a, 0x03, 0x4e,
	0x45, 0x57, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01,
	0x12, 0x08, 0x0a, 0x04, 0x4c, 0x4f, 0x53, 0x54, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x45,
	0x54, 0x49, 0x52, 0x45, 0x44, 0x10, 0x03, 0x42, 0x2a, 0x5a, 0x28, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x3b, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65,
	0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_trainers_proto_rawDescOnce sync.Once
	file_trainers_proto_rawDescData = file_trainers_proto_rawDesc
)

func file_trainers_proto_rawDescGZIP() []byte {
	file_trainers_proto_rawDescOnce.Do(func() {
		file_trainers_proto_rawDescData = protoimpl.X.CompressGZIP(file_trainers_proto_rawDescData)
	})
	return file_trainers_proto_rawDescData
}

var file_trainers_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_trainers_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_trainers_proto_goTypes = []interface{}{
	(SurfaceType)(0),   // 0: main.SurfaceType
	(TrainerStatus)(0), // 1: main.TrainerStatus
	(*Trainer)(nil),    // 2: main.Trainer
}
var file_trainers_proto_depIdxs = []int32{
	0, // 0: main.Trainer.surface_type:type_name -> main.SurfaceType
	1, // 1: main.Trainer.status:type_name -> main.TrainerStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_trainers_proto_init() }
func file_trainers_proto_init() {
	if File_trainers_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_trainers_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Trainer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_trainers_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trainers_proto_goTypes,
		DependencyIndexes: file_trainers_proto_depIdxs,
		EnumInfos:         file_trainers_proto_enumTypes,
		MessageInfos:      file_trainers_proto_msgTypes,
	}.Build()
	File_trainers_proto = out.File
	file_trainers_proto_rawDesc = nil
	file_trainers_proto_goTypes = nil
	file_trainers_proto_depIdxs = nil
}
