// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.0
// source: requests.proto

package running_trackerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order int32

const (
	Order_ASC  Order = 0
	Order_DESC Order = 1
)

// Enum value maps for Order.
var (
	Order_name = map[int32]string{
		0: "ASC",
		1: "DESC",
	}
	Order_value = map[string]int32{
		"ASC":  0,
		"DESC": 1,
	}
)

func (x Order) Enum() *Order {
	p := new(Order)
	*p = x
	return p
}

func (x Order) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Order) Descriptor() protoreflect.EnumDescriptor {
	return file_requests_proto_enumTypes[0].Descriptor()
}

func (Order) Type() protoreflect.EnumType {
	return &file_requests_proto_enumTypes[0]
}

func (x Order) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Order.Descriptor instead.
func (Order) EnumDescriptor() ([]byte, []int) {
	return file_requests_proto_rawDescGZIP(), []int{0}
}

type SortField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Order         Order                  `protobuf:"varint,2,opt,name=order,proto3,enum=main.Order" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortField) Reset() {
	*x = SortField{}
	mi := &file_requests_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortField) ProtoMessage() {}

func (x *SortField) ProtoReflect() protoreflect.Message {
	mi := &file_requests_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortField.ProtoReflect.Descriptor instead.
func (*SortField) Descriptor() ([]byte, []int) {
	return file_requests_proto_rawDescGZIP(), []int{0}
}

func (x *SortField) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *SortField) GetOrder() Order {
	if x != nil {
		return x.Order
	}
	return Order_ASC
}

type AddTrainersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trainers      []*Trainer             `protobuf:"bytes,1,rep,name=trainers,proto3" json:"trainers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTrainersRequest) Reset() {
	*x = AddTrainersRequest{}
	mi := &file_requests_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTrainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTrainersRequest) ProtoMessage() {}

func (x *AddTrainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requests_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTrainersRequest.ProtoReflect.Descriptor instead.
func (*AddTrainersRequest) Descriptor() ([]byte, []int) {
	return file_requests_proto_rawDescGZIP(), []int{1}
}

func (x *AddTrainersRequest) GetTrainers() []*Trainer {
	if x != nil {
		return x.Trainers
	}
	return nil
}

type GetTrainersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trainers      *Trainer               `protobuf:"bytes,1,opt,name=trainers,proto3" json:"trainers,omitempty"`
	SortBy        []*SortField           `protobuf:"bytes,2,rep,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrainersRequest) Reset() {
	*x = GetTrainersRequest{}
	mi := &file_requests_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrainersRequest) ProtoMessage() {}

func (x *GetTrainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requests_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrainersRequest.ProtoReflect.Descriptor instead.
func (*GetTrainersRequest) Descriptor() ([]byte, []int) {
	return file_requests_proto_rawDescGZIP(), []int{2}
}

func (x *GetTrainersRequest) GetTrainers() *Trainer {
	if x != nil {
		return x.Trainers
	}
	return nil
}

func (x *GetTrainersRequest) GetSortBy() []*SortField {
	if x != nil {
		return x.SortBy
	}
	return nil
}

type UpdateTrainersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trainers      []*Trainer             `protobuf:"bytes,1,rep,name=trainers,proto3" json:"trainers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTrainersRequest) Reset() {
	*x = UpdateTrainersRequest{}
	mi := &file_requests_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTrainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTrainersRequest) ProtoMessage() {}

func (x *UpdateTrainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requests_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTrainersRequest.ProtoReflect.Descriptor instead.
func (*UpdateTrainersRequest) Descriptor() ([]byte, []int) {
	return file_requests_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTrainersRequest) GetTrainers() []*Trainer {
	if x != nil {
		return x.Trainers
	}
	return nil
}

type DeleteTrainersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTrainersRequest) Reset() {
	*x = DeleteTrainersRequest{}
	mi := &file_requests_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTrainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTrainersRequest) ProtoMessage() {}

func (x *DeleteTrainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requests_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTrainersRequest.ProtoReflect.Descriptor instead.
func (*DeleteTrainersRequest) Descriptor() ([]byte, []int) {
	return file_requests_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteTrainersRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_requests_proto protoreflect.FileDescriptor

const file_requests_proto_rawDesc = "" +
	"\n" +
	"\x0erequests.proto\x12\x04main\x1a\x0etrainers.proto\"D\n" +
	"\tSortField\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12!\n" +
	"\x05order\x18\x02 \x01(\x0e2\v.main.OrderR\x05order\"?\n" +
	"\x12AddTrainersRequest\x12)\n" +
	"\btrainers\x18\x01 \x03(\v2\r.main.TrainerR\btrainers\"i\n" +
	"\x12GetTrainersRequest\x12)\n" +
	"\btrainers\x18\x01 \x01(\v2\r.main.TrainerR\btrainers\x12(\n" +
	"\asort_by\x18\x02 \x03(\v2\x0f.main.SortFieldR\x06sortBy\"B\n" +
	"\x15UpdateTrainersRequest\x12)\n" +
	"\btrainers\x18\x01 \x03(\v2\r.main.TrainerR\btrainers\")\n" +
	"\x15DeleteTrainersRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids*\x1a\n" +
	"\x05Order\x12\a\n" +
	"\x03ASC\x10\x00\x12\b\n" +
	"\x04DESC\x10\x01B*Z(/proto/generated_files;running_trackerpbb\x06proto3"

var (
	file_requests_proto_rawDescOnce sync.Once
	file_requests_proto_rawDescData []byte
)

func file_requests_proto_rawDescGZIP() []byte {
	file_requests_proto_rawDescOnce.Do(func() {
		file_requests_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_requests_proto_rawDesc), len(file_requests_proto_rawDesc)))
	})
	return file_requests_proto_rawDescData
}

var file_requests_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_requests_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_requests_proto_goTypes = []any{
	(Order)(0),                    // 0: main.Order
	(*SortField)(nil),             // 1: main.SortField
	(*AddTrainersRequest)(nil),    // 2: main.AddTrainersRequest
	(*GetTrainersRequest)(nil),    // 3: main.GetTrainersRequest
	(*UpdateTrainersRequest)(nil), // 4: main.UpdateTrainersRequest
	(*DeleteTrainersRequest)(nil), // 5: main.DeleteTrainersRequest
	(*Trainer)(nil),               // 6: main.Trainer
}
var file_requests_proto_depIdxs = []int32{
	0, // 0: main.SortField.order:type_name -> main.Order
	6, // 1: main.AddTrainersRequest.trainers:type_name -> main.Trainer
	6, // 2: main.GetTrainersRequest.trainers:type_name -> main.Trainer
	1, // 3: main.GetTrainersRequest.sort_by:type_name -> main.SortField
	6, // 4: main.UpdateTrainersRequest.trainers:type_name -> main.Trainer
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_requests_proto_init() }
func file_requests_proto_init() {
	if File_requests_proto != nil {
		return
	}
	file_trainers_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_requests_proto_rawDesc), len(file_requests_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_requests_proto_goTypes,
		DependencyIndexes: file_requests_proto_depIdxs,
		EnumInfos:         file_requests_proto_enumTypes,
		MessageInfos:      file_requests_proto_msgTypes,
	}.Build()
	File_requests_proto = out.File
	file_requests_proto_goTypes = nil
	file_requests_proto_depIdxs = nil
}
