// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.0
// source: requests.proto

package running_trackerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddTrainersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trainers      []*Trainer             `protobuf:"bytes,1,rep,name=trainers,proto3" json:"trainers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTrainersRequest) Reset() {
	*x = AddTrainersRequest{}
	mi := &file_requests_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTrainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTrainersRequest) ProtoMessage() {}

func (x *AddTrainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requests_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTrainersRequest.ProtoReflect.Descriptor instead.
func (*AddTrainersRequest) Descriptor() ([]byte, []int) {
	return file_requests_proto_rawDescGZIP(), []int{0}
}

func (x *AddTrainersRequest) GetTrainers() []*Trainer {
	if x != nil {
		return x.Trainers
	}
	return nil
}

var File_requests_proto protoreflect.FileDescriptor

const file_requests_proto_rawDesc = "" +
	"\n" +
	"\x0erequests.proto\x12\x04main\x1a\x0etrainers.proto\"?\n" +
	"\x12AddTrainersRequest\x12)\n" +
	"\btrainers\x18\x01 \x03(\v2\r.main.TrainerR\btrainersB*Z(/proto/generated_files;running_trackerpbb\x06proto3"

var (
	file_requests_proto_rawDescOnce sync.Once
	file_requests_proto_rawDescData []byte
)

func file_requests_proto_rawDescGZIP() []byte {
	file_requests_proto_rawDescOnce.Do(func() {
		file_requests_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_requests_proto_rawDesc), len(file_requests_proto_rawDesc)))
	})
	return file_requests_proto_rawDescData
}

var file_requests_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_requests_proto_goTypes = []any{
	(*AddTrainersRequest)(nil), // 0: main.AddTrainersRequest
	(*Trainer)(nil),            // 1: main.Trainer
}
var file_requests_proto_depIdxs = []int32{
	1, // 0: main.AddTrainersRequest.trainers:type_name -> main.Trainer
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_requests_proto_init() }
func file_requests_proto_init() {
	if File_requests_proto != nil {
		return
	}
	file_trainers_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_requests_proto_rawDesc), len(file_requests_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_requests_proto_goTypes,
		DependencyIndexes: file_requests_proto_depIdxs,
		MessageInfos:      file_requests_proto_msgTypes,
	}.Build()
	File_requests_proto = out.File
	file_requests_proto_goTypes = nil
	file_requests_proto_depIdxs = nil
}
