// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.0
// source: responses.proto

package running_trackerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddTrainersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Ids           []string               `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTrainersResponse) Reset() {
	*x = AddTrainersResponse{}
	mi := &file_responses_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTrainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTrainersResponse) ProtoMessage() {}

func (x *AddTrainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_responses_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTrainersResponse.ProtoReflect.Descriptor instead.
func (*AddTrainersResponse) Descriptor() ([]byte, []int) {
	return file_responses_proto_rawDescGZIP(), []int{0}
}

func (x *AddTrainersResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddTrainersResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetTrainersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Trainers      []*Trainer             `protobuf:"bytes,2,rep,name=trainers,proto3" json:"trainers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrainersResponse) Reset() {
	*x = GetTrainersResponse{}
	mi := &file_responses_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrainersResponse) ProtoMessage() {}

func (x *GetTrainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_responses_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrainersResponse.ProtoReflect.Descriptor instead.
func (*GetTrainersResponse) Descriptor() ([]byte, []int) {
	return file_responses_proto_rawDescGZIP(), []int{1}
}

func (x *GetTrainersResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetTrainersResponse) GetTrainers() []*Trainer {
	if x != nil {
		return x.Trainers
	}
	return nil
}

var File_responses_proto protoreflect.FileDescriptor

const file_responses_proto_rawDesc = "" +
	"\n" +
	"\x0fresponses.proto\x12\x04main\x1a\x0etrainers.proto\"A\n" +
	"\x13AddTrainersResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids\"Z\n" +
	"\x13GetTrainersResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12)\n" +
	"\btrainers\x18\x02 \x03(\v2\r.main.TrainerR\btrainersB*Z(/proto/generated_files;running_trackerpbb\x06proto3"

var (
	file_responses_proto_rawDescOnce sync.Once
	file_responses_proto_rawDescData []byte
)

func file_responses_proto_rawDescGZIP() []byte {
	file_responses_proto_rawDescOnce.Do(func() {
		file_responses_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_responses_proto_rawDesc), len(file_responses_proto_rawDesc)))
	})
	return file_responses_proto_rawDescData
}

var file_responses_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_responses_proto_goTypes = []any{
	(*AddTrainersResponse)(nil), // 0: main.AddTrainersResponse
	(*GetTrainersResponse)(nil), // 1: main.GetTrainersResponse
	(*Trainer)(nil),             // 2: main.Trainer
}
var file_responses_proto_depIdxs = []int32{
	2, // 0: main.GetTrainersResponse.trainers:type_name -> main.Trainer
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_responses_proto_init() }
func file_responses_proto_init() {
	if File_responses_proto != nil {
		return
	}
	file_trainers_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_responses_proto_rawDesc), len(file_responses_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_responses_proto_goTypes,
		DependencyIndexes: file_responses_proto_depIdxs,
		MessageInfos:      file_responses_proto_msgTypes,
	}.Build()
	File_responses_proto = out.File
	file_responses_proto_goTypes = nil
	file_responses_proto_depIdxs = nil
}
