// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.0
// source: rpc.proto

package running_trackerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_rpc_proto protoreflect.FileDescriptor

const file_rpc_proto_rawDesc = "" +
	"\n" +
	"\trpc.proto\x12\x04main\x1a\x0fresponses.proto\x1a\x0erequests.proto2\xe9\x01\n" +
	"\x0fTrainersService\x12C\n" +
	"\fadd_trainers\x12\x18.main.AddTrainersRequest\x1a\x19.main.AddTrainersResponse\x12C\n" +
	"\fget_trainers\x12\x18.main.GetTrainersRequest\x1a\x19.main.GetTrainersResponse\x12L\n" +
	"\x0fupdate_trainers\x12\x1b.main.UpdateTrainersRequest\x1a\x1c.main.UpdateTrainersResponseB*Z(/proto/generated_files;running_trackerpbb\x06proto3"

var file_rpc_proto_goTypes = []any{
	(*AddTrainersRequest)(nil),     // 0: main.AddTrainersRequest
	(*GetTrainersRequest)(nil),     // 1: main.GetTrainersRequest
	(*UpdateTrainersRequest)(nil),  // 2: main.UpdateTrainersRequest
	(*AddTrainersResponse)(nil),    // 3: main.AddTrainersResponse
	(*GetTrainersResponse)(nil),    // 4: main.GetTrainersResponse
	(*UpdateTrainersResponse)(nil), // 5: main.UpdateTrainersResponse
}
var file_rpc_proto_depIdxs = []int32{
	0, // 0: main.TrainersService.add_trainers:input_type -> main.AddTrainersRequest
	1, // 1: main.TrainersService.get_trainers:input_type -> main.GetTrainersRequest
	2, // 2: main.TrainersService.update_trainers:input_type -> main.UpdateTrainersRequest
	3, // 3: main.TrainersService.add_trainers:output_type -> main.AddTrainersResponse
	4, // 4: main.TrainersService.get_trainers:output_type -> main.GetTrainersResponse
	5, // 5: main.TrainersService.update_trainers:output_type -> main.UpdateTrainersResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_proto_init() }
func file_rpc_proto_init() {
	if File_rpc_proto != nil {
		return
	}
	file_responses_proto_init()
	file_requests_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_proto_goTypes,
		DependencyIndexes: file_rpc_proto_depIdxs,
	}.Build()
	File_rpc_proto = out.File
	file_rpc_proto_goTypes = nil
	file_rpc_proto_depIdxs = nil
}
