// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.0
// source: trainers.proto

package running_trackerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SurfaceType int32

const (
	SurfaceType_UNSPECIFIED   SurfaceType = 0
	SurfaceType_ROAD          SurfaceType = 1
	SurfaceType_TRAIL         SurfaceType = 2
	SurfaceType_ROAD_TO_TRAIL SurfaceType = 3
	SurfaceType_TREADMILL     SurfaceType = 4
)

// Enum value maps for SurfaceType.
var (
	SurfaceType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "ROAD",
		2: "TRAIL",
		3: "ROAD_TO_TRAIL",
		4: "TREADMILL",
	}
	SurfaceType_value = map[string]int32{
		"UNSPECIFIED":   0,
		"ROAD":          1,
		"TRAIL":         2,
		"ROAD_TO_TRAIL": 3,
		"TREADMILL":     4,
	}
)

func (x SurfaceType) Enum() *SurfaceType {
	p := new(SurfaceType)
	*p = x
	return p
}

func (x SurfaceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SurfaceType) Descriptor() protoreflect.EnumDescriptor {
	return file_trainers_proto_enumTypes[0].Descriptor()
}

func (SurfaceType) Type() protoreflect.EnumType {
	return &file_trainers_proto_enumTypes[0]
}

func (x SurfaceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SurfaceType.Descriptor instead.
func (SurfaceType) EnumDescriptor() ([]byte, []int) {
	return file_trainers_proto_rawDescGZIP(), []int{0}
}

type TrainerStatus int32

const (
	TrainerStatus_NEW     TrainerStatus = 0
	TrainerStatus_ACTIVE  TrainerStatus = 1
	TrainerStatus_LOST    TrainerStatus = 2
	TrainerStatus_RETIRED TrainerStatus = 3
)

// Enum value maps for TrainerStatus.
var (
	TrainerStatus_name = map[int32]string{
		0: "NEW",
		1: "ACTIVE",
		2: "LOST",
		3: "RETIRED",
	}
	TrainerStatus_value = map[string]int32{
		"NEW":     0,
		"ACTIVE":  1,
		"LOST":    2,
		"RETIRED": 3,
	}
)

func (x TrainerStatus) Enum() *TrainerStatus {
	p := new(TrainerStatus)
	*p = x
	return p
}

func (x TrainerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrainerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_trainers_proto_enumTypes[1].Descriptor()
}

func (TrainerStatus) Type() protoreflect.EnumType {
	return &file_trainers_proto_enumTypes[1]
}

func (x TrainerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrainerStatus.Descriptor instead.
func (TrainerStatus) EnumDescriptor() ([]byte, []int) {
	return file_trainers_proto_rawDescGZIP(), []int{1}
}

type Trainer struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Brand            string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Model            string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	PurchaseDate     string                 `protobuf:"bytes,3,opt,name=purchase_date,json=purchaseDate,proto3" json:"purchase_date,omitempty"`
	ExpectedLifespan int64                  `protobuf:"varint,4,opt,name=expected_lifespan,json=expectedLifespan,proto3" json:"expected_lifespan,omitempty"`
	SurfaceType      SurfaceType            `protobuf:"varint,5,opt,name=surface_type,json=surfaceType,proto3,enum=main.SurfaceType" json:"surface_type,omitempty"`
	Status           TrainerStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=main.TrainerStatus" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Trainer) Reset() {
	*x = Trainer{}
	mi := &file_trainers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trainer) ProtoMessage() {}

func (x *Trainer) ProtoReflect() protoreflect.Message {
	mi := &file_trainers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trainer.ProtoReflect.Descriptor instead.
func (*Trainer) Descriptor() ([]byte, []int) {
	return file_trainers_proto_rawDescGZIP(), []int{0}
}

func (x *Trainer) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Trainer) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Trainer) GetPurchaseDate() string {
	if x != nil {
		return x.PurchaseDate
	}
	return ""
}

func (x *Trainer) GetExpectedLifespan() int64 {
	if x != nil {
		return x.ExpectedLifespan
	}
	return 0
}

func (x *Trainer) GetSurfaceType() SurfaceType {
	if x != nil {
		return x.SurfaceType
	}
	return SurfaceType_UNSPECIFIED
}

func (x *Trainer) GetStatus() TrainerStatus {
	if x != nil {
		return x.Status
	}
	return TrainerStatus_NEW
}

type AddTrainersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trainers      []*Trainer             `protobuf:"bytes,1,rep,name=trainers,proto3" json:"trainers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTrainersRequest) Reset() {
	*x = AddTrainersRequest{}
	mi := &file_trainers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTrainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTrainersRequest) ProtoMessage() {}

func (x *AddTrainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trainers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTrainersRequest.ProtoReflect.Descriptor instead.
func (*AddTrainersRequest) Descriptor() ([]byte, []int) {
	return file_trainers_proto_rawDescGZIP(), []int{1}
}

func (x *AddTrainersRequest) GetTrainers() []*Trainer {
	if x != nil {
		return x.Trainers
	}
	return nil
}

var File_trainers_proto protoreflect.FileDescriptor

const file_trainers_proto_rawDesc = "" +
	"\n" +
	"\x0etrainers.proto\x12\x04main\x1a\x0eresponse.proto\"\xea\x01\n" +
	"\aTrainer\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12#\n" +
	"\rpurchase_date\x18\x03 \x01(\tR\fpurchaseDate\x12+\n" +
	"\x11expected_lifespan\x18\x04 \x01(\x03R\x10expectedLifespan\x124\n" +
	"\fsurface_type\x18\x05 \x01(\x0e2\x11.main.SurfaceTypeR\vsurfaceType\x12+\n" +
	"\x06status\x18\x06 \x01(\x0e2\x13.main.TrainerStatusR\x06status\"?\n" +
	"\x12AddTrainersRequest\x12)\n" +
	"\btrainers\x18\x01 \x03(\v2\r.main.TrainerR\btrainers*U\n" +
	"\vSurfaceType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\b\n" +
	"\x04ROAD\x10\x01\x12\t\n" +
	"\x05TRAIL\x10\x02\x12\x11\n" +
	"\rROAD_TO_TRAIL\x10\x03\x12\r\n" +
	"\tTREADMILL\x10\x04*;\n" +
	"\rTrainerStatus\x12\a\n" +
	"\x03NEW\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\b\n" +
	"\x04LOST\x10\x02\x12\v\n" +
	"\aRETIRED\x10\x032K\n" +
	"\x0fTrainersService\x128\n" +
	"\fadd_trainers\x12\x18.main.AddTrainersRequest\x1a\x0e.main.ResponseB*Z(/proto/generated_files;running_trackerpbb\x06proto3"

var (
	file_trainers_proto_rawDescOnce sync.Once
	file_trainers_proto_rawDescData []byte
)

func file_trainers_proto_rawDescGZIP() []byte {
	file_trainers_proto_rawDescOnce.Do(func() {
		file_trainers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trainers_proto_rawDesc), len(file_trainers_proto_rawDesc)))
	})
	return file_trainers_proto_rawDescData
}

var file_trainers_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_trainers_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_trainers_proto_goTypes = []any{
	(SurfaceType)(0),           // 0: main.SurfaceType
	(TrainerStatus)(0),         // 1: main.TrainerStatus
	(*Trainer)(nil),            // 2: main.Trainer
	(*AddTrainersRequest)(nil), // 3: main.AddTrainersRequest
	(*Response)(nil),           // 4: main.Response
}
var file_trainers_proto_depIdxs = []int32{
	0, // 0: main.Trainer.surface_type:type_name -> main.SurfaceType
	1, // 1: main.Trainer.status:type_name -> main.TrainerStatus
	2, // 2: main.AddTrainersRequest.trainers:type_name -> main.Trainer
	3, // 3: main.TrainersService.add_trainers:input_type -> main.AddTrainersRequest
	4, // 4: main.TrainersService.add_trainers:output_type -> main.Response
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_trainers_proto_init() }
func file_trainers_proto_init() {
	if File_trainers_proto != nil {
		return
	}
	file_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trainers_proto_rawDesc), len(file_trainers_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trainers_proto_goTypes,
		DependencyIndexes: file_trainers_proto_depIdxs,
		EnumInfos:         file_trainers_proto_enumTypes,
		MessageInfos:      file_trainers_proto_msgTypes,
	}.Build()
	File_trainers_proto = out.File
	file_trainers_proto_goTypes = nil
	file_trainers_proto_depIdxs = nil
}
